let searchable = [
  '<a class="map-link" href="uc.html">Bill S. Cole University Center (UCTR) E5</a>',
  '<a class="map-link" href="chapel.html">Boswell Chapel E6</a>',
  '<a class="map-link" href="admin.html">Administration Building D5</a>',
  '<a class="map-link" href="cbcc.html">Chickasaw Business & Conference Center (CBCC) B3</a>',
  '<a class="map-link" href="danley.html">Danley Hall (DANL) C5</a>',
  '<a class="map-link" href="research.html">Dr. Raniyah Ramadan Center for Undergraduate Research & Learning D6</a>',
  '<a class="map-link" href="bookstore.html">ECU Bookstore F6</a>',
  '<a class="map-link" href="ecupolice.html">ECU Police B3</a>',
  '<a class="map-link" href="faust.html">Faust Hall (FAUS) D4</a>',
  '<a class="map-link" href="fentem.html">Fentem Hall (FENT) B6</a>',
  '<a class="map-link" href="arts.html">Hallie Brown Ford Fine Arts Center (FFAC) B4</a>',
  '<a class="map-link" href="horace.html">Horace Mann (HOMN) C4</a>',
  '<a class="map-link" href="kin.html">Kinesiology Building (KIN) F6</a>',
  '<a class="map-link" href="">Lanoy Education Building (EDUC) D6</a>',
  '<a class="map-link" href="">Linscheid Library & Annex (LLIB) D6</a>',
  '<a class="map-link" href="">Memorial Student Union F6</a>',
  '<a class="map-link" href="">Physical & Environmental Science Center (PES) B5</a>',
  '<a class="map-link" href="">Physical Plant D10</a>',
  '<a class="map-link" href="schl.html">Science Hall (SCHL) C5</a>',
  '<a class="map-link" href="afnd.html">Sterling L. Williams Foundation & Alumni Center F5</a>',
  '<a class="map-link" href="taff.html">Taff Cafeteria G6</a>',
  '<a class="map-link" href="ecubbl.html">Baseball Locker Room G10</a>',
  '<a class="map-link" href="egab.html">Elvan George Athletic Building E9</a>',
  '<a class="map-link" href="">Intramural Practice Field E10, G10</a>',
  '<a class="map-link" href="ecubb.html">Ken Turner Baseball Field F11</a>',
  '<a class="map-link" href="kerr.html">Kerr Activities Center (KACT) G7</a>',
  '<a class="map-link" href="stadium.html">Koi lshto Stadium F9</a>',
  '<a class="map-link" href="mayhue.html">Mayhue Tennis Courts G5</a>',
  '<a class="map-link" href="mcbride.html">McBride Gymnasium E5</a>',
  '<a class="map-link" href="norris.html">Norris Field F9</a>',
  '<a class="map-link" href="">Oscar Parker Tennis Courts E7</a>',
  '<a class="map-link" href="">Pat ONeal Strength & Conditioning Center F10</a>',
  '<a class="map-link" href="">Sand Volleyball Court F7</a>',
  '<a class="map-link" href="">Soccer-Softball Locker Room H11</a>',
  '<a class="map-link" href="">Tiger Soccer Field I11</a>',
  '<a class="map-link" href="">Tiger Softball Field G11</a>',
];
