let searchable = [
  '<a class="map-link" href="uc.html">Bill S. Cole University Center (UCTR) E5</a>',
  '<a class="map-link" href="">Boswell Chapel E6</a>',
  '<a class="map-link" href="">Administration Building D5</a>',
  '<a class="map-link" href="cbcc.html">Chickasaw Business & Conference Center (CBCC) B3</a>',
  '<a class="map-link" href="">Danley Hall (DANL) C5</a>',
  '<a class="map-link" href="">Dr. Raniyah Ramadan Center for Undergraduate Research & Learning D6</a>',
  '<a class="map-link" href="">ECU Bookstore F6</a>',
  '<a class="map-link" href="">ECU Police B3</a>',
  '<a class="map-link" href="">Faust Hall (FAUS) D4</a>',
  '<a class="map-link" href="">Fentem Hall (FENT) B6</a>',
  '<a class="map-link" href="">Hallie Brown Ford Fine Arts Center (FFAC) B4</a>',
  '<a class="map-link" href="">Horace Mann (HOMN) C4</a>',
  '<a class="map-link" href="">Kinesiology Building (KIN) F6</a>',
  '<a class="map-link" href="">Lanoy Education Building (EDUC) D6</a>',
  '<a class="map-link" href="">Linscheid Library & Annex (LLIB) D6</a>',
  '<a class="map-link" href="">Memorial Student Union F6</a>',
  '<a class="map-link" href="">Physical & Environmental Science Center (PES) B5</a>',
  '<a class="map-link" href="">Physical Plant D10</a>',
  '<a class="map-link" href="">Science Hall (SCHL) C5</a>',
  '<a class="map-link" href="">Sterling L. Williams Foundation & Alumni Center F5</a>',
  '<a class="map-link" href="">Taff Cafeteria G6</a>',
  '<a class="map-link" href="">Baseball Locker Room G10</a>',
  '<a class="map-link" href="">Elvan George Athletic Building E9</a>',
  '<a class="map-link" href="">Intramural Practice Field E10, G10</a>',
  '<a class="map-link" href="">Ken Turner Baseball Field F11</a>',
  '<a class="map-link" href="">Kerr Activities Center (KACT) G7</a>',
  '<a class="map-link" href="">Koi lshto Stadium F9</a>',
  '<a class="map-link" href="">Mayhue Tennis Courts G5</a>',
  '<a class="map-link" href="">McBride Gymnasium E5</a>',
  '<a class="map-link" href="">Norris Field F9</a>',
  '<a class="map-link" href="">Oscar Parker Tennis Courts E7</a>',
  '<a class="map-link" href="">Outdoor Basketball Court E7</a>',
  '<a class="map-link" href="">Pat ONeal Strength & Conditioning Center F10</a>',
  '<a class="map-link" href="">Sand Volleyball Court F7</a>',
  '<a class="map-link" href="">Soccer-Softball Locker Room H11</a>',
  '<a class="map-link" href="">Tiger Soccer Field I11</a>',
  '<a class="map-link" href="">Tiger Softball Field G11</a>',
];
